name: Cache Dependencies

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      malloc-impl:
        required: true
        type: string
      prerelease:
        required: true
        type: string

jobs:
  SislDeps:
    uses: eBay/sisl/.github/workflows/build_dependencies.yml@master
    with:
      branch: master
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
  NuraftMesgDeps:
    needs: SislDeps
    uses: ./.github/workflows/build_dependencies.yml
    with:
      branch: main
      build-type: ${{ inputs.build-type }}
      malloc-impl: ${{ inputs.malloc-impl }}
      prerelease: ${{ inputs.prerelease }}
  BuildCommit:
    needs: NuraftMesgDeps
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Setup Conan
      run: |
        python -m pip install --upgrade pip
        python -m pip install conan~=1.0
        conan user
        conan profile new --detect default
        # Set std::string to non-CoW C++11 version
        sed -i 's,compiler.libcxx=libstdc++$,compiler.libcxx=libstdc++11,g' ~/.conan/profiles/default

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Restore Sisl 3rdParty Cache
      id: restore-cache-sisl
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: SislDeps-${{ inputs.build-type }}-${{ inputs.malloc-impl }}-${{ inputs.prerelease }}

    - name: Restore NuraftMesg 3rdParty Cache
      id: restore-3rd-party
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.conan/data
        key: NuMesgDeps-${{ inputs.build-type }}-${{ inputs.malloc-impl }}

    - name: Build
      run: |
        conan create \
            -o sisl:prerelease=${{ inputs.prerelease }} \
            -o sisl:malloc_impl=${{ inputs.malloc-impl }} \
            -o sisl:testing=False \
            -s build_type=${{ inputs.build-type }} \
            --build missing \
            . \
            oss/main
